language: python
os: linux
# Each attribute in the matrix will override the global attribute.
matrix:
  fast_finish: true
  allow_failures:
    # MacOS is high latency to execute on Travis CI, don't wait.
    # Plus some osx_image configs (xcode8.3) exhibit odd test failures.
    - os: osx
  include:
    - python: 2.7
      deploy:
        provider: pypi
        user: "GregoryPSmith"
        password: $TEST_PYPI_PASSWORD
        server: https://test.pypi.org/legacy/
        on:
          tags: true
          branch: travis-to-test-pypi
        # No wheels for Linux (manylinux1 is too old)
        distributions: sdist
    - python: 2.6
      # Python 2.6 does not have test discovery.
      script: python test_subprocess32.py
      env:
        - LANG=C
    - python: 3.5
      # Just check that the dummy shim installs and works on 3.x.
      script: |
        cd /  # We cannot be in the directory with subprocess32.py in it.
        python -c 'import os, subprocess32, subprocess, sys; print("working directory:", os.getcwd()); print("subprocess32 module is", subprocess32); sys.exit(subprocess32 is not subprocess)'
    - os: osx
      # Travis does not have a Python runtime for MacOS.
      #  https://pythonhosted.org/CodeChat/.travis.yml.html
      language: generic
      before_install:
        - pkgutil --pkgs | grep -F "org.python.Python.PythonFramework-2.7" || curl -L -o /tmp/Python.pkg https://www.python.org/ftp/python/2.7.15/python-2.7.15-macosx10.6.pkg && sudo installer -pkg /tmp/Python.pkg -target /
        - pkgutil --pkgs | grep -F "org.python.Python.PythonFramework"
        - export PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
        - which pip2
        - pip2 install --upgrade pip
      install:
        - pip2 -v install .
      deploy:
        provider: pypi
        user: "GregoryPSmith"
        password: $TEST_PYPI_PASSWORD
        server: https://test.pypi.org/legacy/
        on:
          tags: true
          branch: travis-to-test-pypi
        distributions: bdist_wheel
install:
  - pip install .
script:
  - which python
  - python --version
  - python -m unittest discover -v
after_deploy:
  - ls -lR
